server:
  port: 8080


spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/zyc_test?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.exmple.springbootdemo

  spring:
    redis:
      #redis数据库地址
      host: 127.0.0.1
      port: 6379
      password: root
      timeout: 1000
      #redis数据库索引，默认0
      database: 1

debug: true

