server:
  port: 8080

spring:
  datasource:
    name: test
    url: jdbc:mysql://203.33.215.23:3306/gyzg?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: Password12#$
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.exmple.springbootdemo

